name: Server tests

on:
  push:
    paths:
      - server/**

jobs:
  pytest:
    runs-on: self-hosted
    env:
      PIP_ROOT_USER_ACTION: ignore

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12.8
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r server/requirements.txt
        pip install -r server/dev-requirements.txt

    - name: Run tests
      working-directory: ${{github.workspace}}/server
      env:
        PYTHONPATH: ${{github.workspace}}/server
      run: pytest -vv tests
